import type { DocumentPage, ZineDocumentState } from '../../stores/documentStore';

export interface ZineTemplate {
  id: string;
  name: string;
  tagline: string;
  description: string;
  formatId: string;
  paper: ZineDocumentState['paper'];
  activeLookId: string;
  difficulty: 'easy' | 'medium';
  coverBg: string;
  accentColor: string;
  tags: string[];
  pages: DocumentPage[];
}

export const STARTER_TEMPLATES: ZineTemplate[] = [
  {
    id: 'perzine-punk',
    name: 'Perzine: Personal Dispatch',
    tagline: 'Raw photocopy memoir, collage cutouts & tape',
    description:
      'Classic 8-page DIY mini zine inspired by 90s riot grrrl and indie punk perzines. Filled with expressive diary spreads, tape strips, and gritty Xerox aesthetics.',
    formatId: 'mini-8',
    paper: 'letter',
    activeLookId: 'xerox-punk',
    difficulty: 'easy',
    coverBg: '#f2eee6',
    accentColor: '#1a1a1a',
    tags: ['Personal', 'Punk', 'Photocopy', 'Memoir'],
    pages: [
      {
        pageNumber: 1,
        backgroundColor: '#f2eee6',
        objects: [
          {
            id: 'pz-tape-top',
            type: 'sticker',
            stickerType: 'tape-duct',
            xPercent: 0.3,
            yPercent: 0.05,
            wPercent: 0.4,
            hPercent: 0.08,
            rotation: -3,
            opacity: 0.9,
            locked: false,
            hidden: false,
          },
          {
            id: 'pz-title',
            type: 'text',
            text: 'DISTORTION\nISSUE #1',
            xPercent: 0.1,
            yPercent: 0.22,
            wPercent: 0.8,
            hPercent: 0.25,
            rotation: -2,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 22,
            color: '#111111',
            bold: true,
          },
          {
            id: 'pz-subtitle',
            type: 'text',
            text: 'A personal cut-and-paste dispatch from the edge of the screen.',
            xPercent: 0.12,
            yPercent: 0.52,
            wPercent: 0.76,
            hPercent: 0.15,
            rotation: 1,
            opacity: 0.9,
            locked: false,
            hidden: false,
            fontSizePt: 10,
            color: '#333333',
            bold: false,
          },
          {
            id: 'pz-tape-bot',
            type: 'sticker',
            stickerType: 'tape-masking',
            xPercent: 0.2,
            yPercent: 0.82,
            wPercent: 0.5,
            hPercent: 0.07,
            rotation: 2,
            opacity: 0.85,
            locked: false,
            hidden: false,
          },
        ],
      },
      {
        pageNumber: 2,
        backgroundColor: '#f6f3ec',
        objects: [
          {
            id: 'pz-p2-head',
            type: 'text',
            text: '01 // MIDNIGHT RAMBLING',
            xPercent: 0.1,
            yPercent: 0.08,
            wPercent: 0.8,
            hPercent: 0.1,
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 12,
            color: '#111111',
            bold: true,
          },
          {
            id: 'pz-p2-body',
            type: 'text',
            text: 'I started writing this at 2:40 AM when the neighborhood hum went completely dead. We build machines to connect us, but sometimes the most electric signal is black ink on cheap paper.',
            xPercent: 0.1,
            yPercent: 0.22,
            wPercent: 0.8,
            hPercent: 0.45,
            rotation: 0,
            opacity: 0.9,
            locked: false,
            hidden: false,
            fontSizePt: 9,
            color: '#222222',
            bold: false,
          },
          {
            id: 'pz-p2-staple',
            type: 'sticker',
            stickerType: 'staple',
            xPercent: 0.4,
            yPercent: 0.8,
            wPercent: 0.15,
            hPercent: 0.05,
            rotation: 90,
            opacity: 0.95,
            locked: false,
            hidden: false,
          },
        ],
      },
      {
        pageNumber: 3,
        backgroundColor: '#f2eee6',
        objects: [
          {
            id: 'pz-p3-box',
            type: 'shape',
            shapeType: 'rect',
            xPercent: 0.1,
            yPercent: 0.15,
            wPercent: 0.8,
            hPercent: 0.5,
            rotation: 1,
            opacity: 0.1,
            locked: false,
            hidden: false,
            fillColor: '#111111',
          },
          {
            id: 'pz-p3-caption',
            type: 'text',
            text: '[PHOTO / POLAROID PLACEHOLDER]\n"The alleyway behind the printer depot"',
            xPercent: 0.15,
            yPercent: 0.35,
            wPercent: 0.7,
            hPercent: 0.15,
            rotation: 1,
            opacity: 0.8,
            locked: false,
            hidden: false,
            fontSizePt: 8,
            color: '#111111',
            bold: false,
          },
          {
            id: 'pz-p3-tape',
            type: 'sticker',
            stickerType: 'tape-clear',
            xPercent: 0.35,
            yPercent: 0.1,
            wPercent: 0.3,
            hPercent: 0.06,
            rotation: -5,
            opacity: 0.6,
            locked: false,
            hidden: false,
          },
        ],
      },
      {
        pageNumber: 4,
        backgroundColor: '#f6f3ec',
        objects: [
          {
            id: 'pz-p4-title',
            type: 'text',
            text: 'SIDE A: TAPE SOUNDS',
            xPercent: 0.1,
            yPercent: 0.08,
            wPercent: 0.8,
            hPercent: 0.1,
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 12,
            color: '#111111',
            bold: true,
          },
          {
            id: 'pz-p4-list',
            type: 'text',
            text: '1. Fugazi - Blueprint\n2. Sleater-Kinney - Dig Me Out\n3. Sonic Youth - Schizophrenia\n4. Beat Happening - Indian Summer\n5. Unwound - Verns Rumor',
            xPercent: 0.12,
            yPercent: 0.22,
            wPercent: 0.76,
            hPercent: 0.45,
            rotation: 0,
            opacity: 0.9,
            locked: false,
            hidden: false,
            fontSizePt: 9,
            color: '#222222',
            bold: false,
          },
          {
            id: 'pz-p4-star',
            type: 'sticker',
            stickerType: 'star',
            xPercent: 0.7,
            yPercent: 0.75,
            wPercent: 0.18,
            hPercent: 0.14,
            rotation: 12,
            opacity: 0.9,
            locked: false,
            hidden: false,
            color: '#111111',
          },
        ],
      },
      {
        pageNumber: 5,
        backgroundColor: '#f2eee6',
        objects: [
          {
            id: 'pz-p5-quote',
            type: 'text',
            text: '"MAKE YOUR OWN CULTURE OR SOMEONE WILL SELL IT BACK TO YOU AT FULL PRICE."',
            xPercent: 0.1,
            yPercent: 0.25,
            wPercent: 0.8,
            hPercent: 0.4,
            rotation: -1,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 13,
            color: '#111111',
            bold: true,
          },
        ],
      },
      {
        pageNumber: 6,
        backgroundColor: '#f6f3ec',
        objects: [
          {
            id: 'pz-p6-head',
            type: 'text',
            text: 'FOUND EPHEMERA',
            xPercent: 0.1,
            yPercent: 0.08,
            wPercent: 0.8,
            hPercent: 0.1,
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 12,
            color: '#111111',
            bold: true,
          },
          {
            id: 'pz-p6-body',
            type: 'text',
            text: 'Keep the ticket stub. Save the torn receipt. Glue it down before the thermal ink fades away into nothingness.',
            xPercent: 0.1,
            yPercent: 0.22,
            wPercent: 0.8,
            hPercent: 0.35,
            rotation: 0,
            opacity: 0.85,
            locked: false,
            hidden: false,
            fontSizePt: 9,
            color: '#222222',
            bold: false,
          },
          {
            id: 'pz-p6-tape',
            type: 'sticker',
            stickerType: 'tape-masking',
            xPercent: 0.25,
            yPercent: 0.7,
            wPercent: 0.45,
            hPercent: 0.08,
            rotation: -4,
            opacity: 0.85,
            locked: false,
            hidden: false,
          },
        ],
      },
      {
        pageNumber: 7,
        backgroundColor: '#f2eee6',
        objects: [
          {
            id: 'pz-p7-head',
            type: 'text',
            text: 'HOW TO FOLD THIS',
            xPercent: 0.1,
            yPercent: 0.08,
            wPercent: 0.8,
            hPercent: 0.1,
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 11,
            color: '#111111',
            bold: true,
          },
          {
            id: 'pz-p7-steps',
            type: 'text',
            text: '1. Fold in half horizontally.\n2. Fold into 8 equal panels.\n3. Slit middle horizontal fold.\n4. Push together into a (+).\n5. Fold into an 8-page book.',
            xPercent: 0.12,
            yPercent: 0.24,
            wPercent: 0.76,
            hPercent: 0.45,
            rotation: 0,
            opacity: 0.85,
            locked: false,
            hidden: false,
            fontSizePt: 8,
            color: '#222222',
            bold: false,
          },
        ],
      },
      {
        pageNumber: 8,
        backgroundColor: '#f2eee6',
        objects: [
          {
            id: 'pz-p8-colophon',
            type: 'text',
            text: 'DISTORTION #1\nPublished everywhere & nowhere.\nCopy freely. Trade wildly.',
            xPercent: 0.1,
            yPercent: 0.25,
            wPercent: 0.8,
            hPercent: 0.25,
            rotation: 0,
            opacity: 0.9,
            locked: false,
            hidden: false,
            fontSizePt: 9,
            color: '#222222',
            bold: false,
          },
          {
            id: 'pz-p8-barcode',
            type: 'sticker',
            stickerType: 'barcode',
            xPercent: 0.25,
            yPercent: 0.62,
            wPercent: 0.5,
            hPercent: 0.16,
            rotation: 0,
            opacity: 0.95,
            locked: false,
            hidden: false,
          },
        ],
      },
    ],
  },
  {
    id: 'art-catalog',
    name: 'Mini Art Catalog',
    tagline: 'Clean gallery spreads, Swiss typography & riso pop',
    description:
      'Contemporary art exhibition pamphlet featuring spacious margins, clean typography, photo frames, and a vibrant Risograph two-color print profile.',
    formatId: 'mini-8',
    paper: 'letter',
    activeLookId: 'riso-pop',
    difficulty: 'easy',
    coverBg: '#fffbf2',
    accentColor: '#0055ff',
    tags: ['Art', 'Catalog', 'Riso', 'Photography', 'Minimal'],
    pages: [
      {
        pageNumber: 1,
        backgroundColor: '#fffbf2',
        objects: [
          {
            id: 'art-dot',
            type: 'shape',
            shapeType: 'circle',
            xPercent: 0.35,
            yPercent: 0.15,
            wPercent: 0.3,
            hPercent: 0.3,
            rotation: 0,
            opacity: 0.85,
            locked: false,
            hidden: false,
            fillColor: '#ff0055',
          },
          {
            id: 'art-title',
            type: 'text',
            text: 'FORMS IN DIALOGUE',
            xPercent: 0.1,
            yPercent: 0.55,
            wPercent: 0.8,
            hPercent: 0.15,
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 16,
            color: '#0033cc',
            bold: true,
          },
          {
            id: 'art-subtitle',
            type: 'text',
            text: 'Recent Sculptures and Ephemera\nAutumn Exhibition 2026',
            xPercent: 0.1,
            yPercent: 0.72,
            wPercent: 0.8,
            hPercent: 0.15,
            rotation: 0,
            opacity: 0.8,
            locked: false,
            hidden: false,
            fontSizePt: 8,
            color: '#111111',
            bold: false,
          },
        ],
      },
      {
        pageNumber: 2,
        backgroundColor: '#ffffff',
        objects: [
          {
            id: 'art-p2-statement',
            type: 'text',
            text: 'CURATORIAL NOTE\n\nThis collection investigates tension between industrial sheet metal and organic degradation. Each piece is cast, oxidized, and allowed to weather over seasonal cycles.',
            xPercent: 0.1,
            yPercent: 0.15,
            wPercent: 0.8,
            hPercent: 0.6,
            rotation: 0,
            opacity: 0.9,
            locked: false,
            hidden: false,
            fontSizePt: 9,
            color: '#111111',
            bold: false,
          },
        ],
      },
      {
        pageNumber: 3,
        backgroundColor: '#fffbf2',
        objects: [
          {
            id: 'art-p3-img-frame',
            type: 'shape',
            shapeType: 'rect',
            xPercent: 0.1,
            yPercent: 0.15,
            wPercent: 0.8,
            hPercent: 0.55,
            rotation: 0,
            opacity: 0.15,
            locked: false,
            hidden: false,
            fillColor: '#0055ff',
          },
          {
            id: 'art-p3-caption',
            type: 'text',
            text: 'Plate 01: Monolith IV\nCast bronze, patina\n24 x 18 x 8 cm',
            xPercent: 0.1,
            yPercent: 0.75,
            wPercent: 0.8,
            hPercent: 0.15,
            rotation: 0,
            opacity: 0.75,
            locked: false,
            hidden: false,
            fontSizePt: 7,
            color: '#0033cc',
            bold: false,
          },
        ],
      },
      {
        pageNumber: 4,
        backgroundColor: '#ffffff',
        objects: [
          {
            id: 'art-p4-img-frame',
            type: 'shape',
            shapeType: 'rect',
            xPercent: 0.1,
            yPercent: 0.15,
            wPercent: 0.8,
            hPercent: 0.55,
            rotation: 0,
            opacity: 0.15,
            locked: false,
            hidden: false,
            fillColor: '#ff0055',
          },
          {
            id: 'art-p4-caption',
            type: 'text',
            text: 'Plate 02: Prismatic Drift\nCold-rolled steel, enamel\n40 x 30 x 12 cm',
            xPercent: 0.1,
            yPercent: 0.75,
            wPercent: 0.8,
            hPercent: 0.15,
            rotation: 0,
            opacity: 0.75,
            locked: false,
            hidden: false,
            fontSizePt: 7,
            color: '#ff0055',
            bold: false,
          },
        ],
      },
      {
        pageNumber: 5,
        backgroundColor: '#fffbf2',
        objects: [
          {
            id: 'art-p5-text',
            type: 'text',
            text: '"FORM DERIVES FROM THE RESISTANCE OF THE RAW MATERIAL."',
            xPercent: 0.1,
            yPercent: 0.3,
            wPercent: 0.8,
            hPercent: 0.3,
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 11,
            color: '#0033cc',
            bold: true,
          },
        ],
      },
      {
        pageNumber: 6,
        backgroundColor: '#ffffff',
        objects: [
          {
            id: 'art-p6-checklist',
            type: 'text',
            text: 'EXHIBITION CHECKLIST\n\n1. Monolith IV (2025)\n2. Prismatic Drift (2025)\n3. Untitled Fragment (2026)\n4. Soil Core Study (2026)',
            xPercent: 0.1,
            yPercent: 0.15,
            wPercent: 0.8,
            hPercent: 0.6,
            rotation: 0,
            opacity: 0.9,
            locked: false,
            hidden: false,
            fontSizePt: 8,
            color: '#111111',
            bold: false,
          },
        ],
      },
      {
        pageNumber: 7,
        backgroundColor: '#fffbf2',
        objects: [
          {
            id: 'art-p7-bio',
            type: 'text',
            text: 'ARTIST BIOGRAPHY\n\nLiving and working in Berlin. Graduate of the Academy of Fine Arts. Works in public collections across Europe.',
            xPercent: 0.1,
            yPercent: 0.2,
            wPercent: 0.8,
            hPercent: 0.5,
            rotation: 0,
            opacity: 0.85,
            locked: false,
            hidden: false,
            fontSizePt: 8,
            color: '#111111',
            bold: false,
          },
        ],
      },
      {
        pageNumber: 8,
        backgroundColor: '#fffbf2',
        objects: [
          {
            id: 'art-p8-colophon',
            type: 'text',
            text: 'EDITION OF 250\nPrinted on 120gsm unbleached vellum.\nType: Helvetica Neue & Courier.\nGallery Edition © 2026.',
            xPercent: 0.1,
            yPercent: 0.3,
            wPercent: 0.8,
            hPercent: 0.3,
            rotation: 0,
            opacity: 0.8,
            locked: false,
            hidden: false,
            fontSizePt: 7,
            color: '#0033cc',
            bold: false,
          },
          {
            id: 'art-p8-barcode',
            type: 'sticker',
            stickerType: 'barcode',
            xPercent: 0.25,
            yPercent: 0.65,
            wPercent: 0.5,
            hPercent: 0.15,
            rotation: 0,
            opacity: 0.9,
            locked: false,
            hidden: false,
          },
        ],
      },
    ],
  },
  {
    id: 'radical-pamphlet',
    name: 'Radical Pamphlet',
    tagline: 'High-contrast agitprop & community action guide',
    description:
      '4-page French quarter-fold pamphlet. Zero scissors or staples needed—just 2 folds. Heavy headlines, community action checklist, and vintage newsprint texture.',
    formatId: 'quarter-fold-4',
    paper: 'letter',
    activeLookId: 'newsprint-noir',
    difficulty: 'easy',
    coverBg: '#eae6de',
    accentColor: '#1a1a1a',
    tags: ['Pamphlet', 'Activism', 'Newsprint', 'No-Cut'],
    pages: [
      {
        pageNumber: 1,
        backgroundColor: '#eae6de',
        objects: [
          {
            id: 'rad-star',
            type: 'sticker',
            stickerType: 'star',
            xPercent: 0.4,
            yPercent: 0.08,
            wPercent: 0.2,
            hPercent: 0.15,
            rotation: 0,
            opacity: 0.95,
            locked: false,
            hidden: false,
            color: '#111111',
          },
          {
            id: 'rad-title',
            type: 'text',
            text: 'SOLIDARITY\nNOW!',
            xPercent: 0.08,
            yPercent: 0.25,
            wPercent: 0.84,
            hPercent: 0.28,
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 24,
            color: '#0a0a0a',
            bold: true,
          },
          {
            id: 'rad-sub',
            type: 'text',
            text: 'A COMMUNITY HANDBOOK FOR MUTUAL AID & COLLECTIVE DEFENSE',
            xPercent: 0.08,
            yPercent: 0.55,
            wPercent: 0.84,
            hPercent: 0.2,
            rotation: 0,
            opacity: 0.9,
            locked: false,
            hidden: false,
            fontSizePt: 10,
            color: '#1a1a1a',
            bold: true,
          },
          {
            id: 'rad-p1-tape',
            type: 'sticker',
            stickerType: 'tape-duct',
            xPercent: 0.2,
            yPercent: 0.82,
            wPercent: 0.6,
            hPercent: 0.08,
            rotation: 1,
            opacity: 0.95,
            locked: false,
            hidden: false,
          },
        ],
      },
      {
        pageNumber: 2,
        backgroundColor: '#ede9e2',
        objects: [
          {
            id: 'rad-p2-head',
            type: 'text',
            text: 'FIVE TENETS OF MUTUAL AID',
            xPercent: 0.08,
            yPercent: 0.08,
            wPercent: 0.84,
            hPercent: 0.12,
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 12,
            color: '#0a0a0a',
            bold: true,
          },
          {
            id: 'rad-p2-body',
            type: 'text',
            text: '1. NOT CHARITY, SOLIDARITY\nAid without paternalism or means testing.\n\n2. DIRECT ACTION\nSolve immediate survival needs directly.\n\n3. SHARED RESOURCES\nTool libraries, seed shares, free pantries.\n\n4. CONSENSUS & TRUST\nDecisions made by all affected voices.',
            xPercent: 0.08,
            yPercent: 0.22,
            wPercent: 0.84,
            hPercent: 0.68,
            rotation: 0,
            opacity: 0.95,
            locked: false,
            hidden: false,
            fontSizePt: 8.5,
            color: '#1a1a1a',
            bold: false,
          },
        ],
      },
      {
        pageNumber: 3,
        backgroundColor: '#ede9e2',
        objects: [
          {
            id: 'rad-p3-head',
            type: 'text',
            text: 'ACTION CHECKLIST',
            xPercent: 0.08,
            yPercent: 0.08,
            wPercent: 0.84,
            hPercent: 0.12,
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 12,
            color: '#0a0a0a',
            bold: true,
          },
          {
            id: 'rad-p3-list',
            type: 'text',
            text: '[✓] Map local neighborhood emergency points\n[✓] Build phone trees that work offline\n[✓] Distribute paper pamphlets door to door\n[✓] Stock community first aid kits\n[✓] Hold weekly open gatherings',
            xPercent: 0.08,
            yPercent: 0.22,
            wPercent: 0.84,
            hPercent: 0.5,
            rotation: 0,
            opacity: 0.95,
            locked: false,
            hidden: false,
            fontSizePt: 8.5,
            color: '#1a1a1a',
            bold: false,
          },
          {
            id: 'rad-p3-arrow',
            type: 'sticker',
            stickerType: 'arrow',
            xPercent: 0.35,
            yPercent: 0.76,
            wPercent: 0.3,
            hPercent: 0.12,
            rotation: -10,
            opacity: 0.9,
            locked: false,
            hidden: false,
            color: '#0a0a0a',
          },
        ],
      },
      {
        pageNumber: 4,
        backgroundColor: '#eae6de',
        objects: [
          {
            id: 'rad-p4-head',
            type: 'text',
            text: 'REPRODUCE & DISTRIBUTE',
            xPercent: 0.08,
            yPercent: 0.15,
            wPercent: 0.84,
            hPercent: 0.15,
            rotation: 0,
            opacity: 1,
            locked: false,
            hidden: false,
            fontSizePt: 14,
            color: '#0a0a0a',
            bold: true,
          },
          {
            id: 'rad-p4-text',
            type: 'text',
            text: 'This pamphlet is free of copyright.\nPhotocopy it at your local library.\nHand it to neighbors.\nDrop it in coffee shops and bookstores.\n\nPrinted on one single sheet.\nTwo folds. Zero cuts.',
            xPercent: 0.08,
            yPercent: 0.34,
            wPercent: 0.84,
            hPercent: 0.4,
            rotation: 0,
            opacity: 0.9,
            locked: false,
            hidden: false,
            fontSizePt: 8.5,
            color: '#222222',
            bold: false,
          },
          {
            id: 'rad-p4-tape',
            type: 'sticker',
            stickerType: 'tape-masking',
            xPercent: 0.25,
            yPercent: 0.8,
            wPercent: 0.5,
            hPercent: 0.08,
            rotation: -2,
            opacity: 0.85,
            locked: false,
            hidden: false,
          },
        ],
      },
    ],
  },
];
